// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SistemaLogs.Api.Migrations
{
    [DbContext(typeof(App2DbContext))]
    [Migration("20250618070925_v01")]
    partial class v01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaLogs.Modelos.AlertaPredictiva", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<int>("CamionCodigo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Codigo");

                    b.ToTable("AlertasPredictivas");
                });

            modelBuilder.Entity("SistemaLogs.Modelos.LogSensor", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<int>("CamionCodigo")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoMotor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaLectura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("integer");

                    b.HasKey("Codigo");

                    b.ToTable("LogsSensores");
                });
#pragma warning restore 612, 618
        }
    }
}
